### ISSUE TITLE
Error not being thrown?

### ISSUE THREAD

**Issue by nitrag** [parse-server-modules/parse-server-sns-adapter#3]
I'm getting this on "npm start", shouldn't I be seeing the actual error message?

```
/Users/ryan/Documents/Parse/parse-offroad-server/node_modules/parse-server-sns-adapter/src/SNSPushAdapter.js:20
        throw new Parse.Error(Parse.Error.PUSH_MISCONFIGURED,
        ^
[object Object]
```

Using node 4.3.1 now.

Also, FYI @rogerhu your pushConfig json variable in the README isn't valid. There's an extra "}".

Also, is the "ARN" the full "ARN" in AWS console(arn:aws:sns:us-east-1:12345677890:app/GCM/appname_MOBILEHUB_12345678) or just the "Name". Confusing because you have us specify the region when it is in the full ARN field. Maybe you didn't want to parse it out?

**Comment by rogerhu** [comment]
Somehow accessKey and secretKey are not being supplied.

Arn is the full arn starting with arn:

**Comment by rogerhu** [comment]
Fixed readme.  For reference you can look at the spec/ tests to see how to instantiate
